name: .NET Core

on:
  push:
    branches: test-dotnet-5 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        dotnet: [ '5.0.100-preview.3.20216.6' ]
    steps:
    - uses: actions/checkout@v2
    - run: dotnet --version || echo 'No dotnet command found'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ runner.dotnet }} #Here should be ${{ matrix.dotnet }}
    - run: dotnet --version || echo 'No dotnet command found'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
